export const GET_DATA = 'GET_DATA';
export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';
export const GET_DATA_FAIL = 'GET_DATA_FAIL';
export const ADD_ITEM = 'ADD_ITEM';
export const REMOVE_ITEM = 'REMOVE_ITEM';
export const MOVE_CONSTRUCTOR_ITEM = 'CONSTRUCTOR_ITEM';
export const POST_ORDER = 'POST_ORDER';
export const GET_INGREDIENT_INFO = 'GET_INGREDIENT_INFO';
export const GET_TOKEN = 'GET_TOKEN';
export const DELETE_TOKEN = 'DELETE_TOKEN'

export const baseUrl = 'https://norma.nomoreparties.space/api';
export const myToken: string = '91089aeb-9e00-4a3f-9cf9-1d0f7117fd38';

export const WS_CONNECTION: 'WS_CONNECTION' = 'WS_CONNECTION';
export const WS_CONNECTION_ORDERS: 'WS_CONNECTION_ORDERS' ='WS_CONNECTION_ORDERS';
export const WS_GET_MESSAGE: 'WS_GET_MESSAGE' = 'WS_GET_MESSAGE';
export const WS_GET_ORDER_MESSAGE: 'WS_GET_ORDER_MESSAGE' ='WS_GET_ORDER_MESSAGE';
export const WS_CONNECTION_SUCCESS: 'WS_CONNECTION_SUCCESS' ='WS_CONNECTION_SUCCESS';
export const WS_CONNECTION_ERROR: 'WS_CONNECTION_ERROR' = 'WS_CONNECTION_ERROR';
export const WS_CONNECTION_CLOSED: 'WS_CONNECTION_CLOSED' ='WS_CONNECTION_CLOSED';
